# Generated by Django 5.2.17 on 2026-09-27 04:33

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('image', models.ImageField(upload_to='category', verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Tên sản phẩm')),
                ('image', models.ImageField(upload_to='', verbose_name='Ảnh chính')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('specifications', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(verbose_name='Giá bán')),
                ('old_price', models.IntegerField(verbose_name='Giá cũ')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('color', models.ManyToManyField(blank=True, to='store.color')),
                ('size', models.ManyToManyField(blank=True, to='store.size')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product-images', verbose_name='Ảnh phụ')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_images', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Tên brand')),
                ('image', models.ImageField(upload_to=store.models.user_directory_path, verbose_name='Logo brand')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.vendor'),
        ),
    ]
